-- AlterTable
ALTER TABLE "Place"
ADD COLUMN IF NOT EXISTS "moderationStatus" VARCHAR(32) NOT NULL DEFAULT 'PENDING',
ADD COLUMN IF NOT EXISTS "externalProvider" VARCHAR(32),
ADD COLUMN IF NOT EXISTS "externalProviderId" VARCHAR(255),
ADD COLUMN IF NOT EXISTS "externalUrl" VARCHAR(500),
ADD COLUMN IF NOT EXISTS "providerMatchConfidence" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "providerMatchedAt" TIMESTAMP(6);
