export const ORGANIZER_PLACE_CLAIM_REVIEWED_NOTIFICATION_TYPE =
  'ORGANIZER_PLACE_CLAIM_REVIEWED' as const;

export const ORGANIZER_NOTIFICATION_TYPES = [
  'ORGANIZER_BOOKING_CREATED',
  'ORGANIZER_EVENT_UPDATED',
  'ORGANIZER_COLLABORATOR_UPDATED',
  'ORGANIZER_EVENT_REMINDER',
  ORGANIZER_PLACE_CLAIM_REVIEWED_NOTIFICATION_TYPE,
  'ORGANIZER_SYSTEM',
] as const;

export type OrganizerNotificationType =
  (typeof ORGANIZER_NOTIFICATION_TYPES)[number];

export type PlaceClaimDecision = 'APPROVED' | 'REJECTED';
