ALTER TABLE "UserSettings"
ADD COLUMN "organizerNotifyBookings" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "organizerNotifyTeamUpdates" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "organizerNotifyReminderD1" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "organizerNotifyReminderH3" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "organizerNotifyReminderH1" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "organizerNotificationPriorityMin" VARCHAR(16) NOT NULL DEFAULT 'IMPORTANT',
ADD COLUMN "organizerScannerOfflineAuto" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "organizerScannerAutoSync" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "organizerScannerHaptics" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "organizerScannerSound" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "organizerScannerStrictWindow" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "organizerDefaultCheckInOpenOffsetMin" INTEGER NOT NULL DEFAULT -60,
ADD COLUMN "organizerDefaultCheckInCloseOffsetMin" INTEGER NOT NULL DEFAULT 180,
ADD COLUMN "organizerDefaultMaxTicketsPerUser" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN "organizerDefaultCancellationPolicy" TEXT,
ADD COLUMN "organizerDefaultRefundPolicy" TEXT,
ADD COLUMN "organizerTeamInviteScope" VARCHAR(24) NOT NULL DEFAULT 'OWNER_ONLY',
ADD COLUMN "organizerTeamDefaultPermission" VARCHAR(16) NOT NULL DEFAULT 'EDIT',
ADD COLUMN "organizerTeamRequireRemovalConfirm" BOOLEAN NOT NULL DEFAULT true;
